spring:
  profiles:
    active: test

  jpa:
    show-sql: false
    properties:
      javax.persistence.validation.mode: none

---
spring:
  profiles: create-db
  
  jpa:
    properties:
      javax.persistence.schema-generation.database.action: drop-and-create
 